cmake_minimum_required(VERSION 3.9)

project(jwm LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(NOT JWM_ARCH)
    if ("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "arm64")
        set(JWM_ARCH "arm64")
    else()
        set(JWM_ARCH "x64")
    endif()
endif()

file(GLOB SOURCES_CXX ${CMAKE_CURRENT_LIST_DIR}/../shared/cc/*.cc ${CMAKE_CURRENT_LIST_DIR}/cc/*.cc ${CMAKE_CURRENT_LIST_DIR}/cc/*.c)
file(GLOB SOURCES_CXX_IMPL ${CMAKE_CURRENT_LIST_DIR}/../shared/cc/impl/*.cc)
set(GENERATED_DIR ${CMAKE_CURRENT_BINARY_DIR}/generated)
find_program(WAYLAND_SCANNER wayland-scanner REQUIRED)
set(XDG_OUTPUT_PROTOCOL_XML ${CMAKE_CURRENT_LIST_DIR}/protocols/xdg-output-unstable-v1.xml)
set(XDG_OUTPUT_PROTOCOL_HEADER ${GENERATED_DIR}/xdg-output-unstable-v1-client-protocol.hh)
set(GENERATED_XDG_OUTPUT_PROTOCOL ${GENERATED_DIR}/xdg-output-unstable-v1-protocol.c)
set(XDG_SHELL_PROTOCOL_XML ${CMAKE_CURRENT_LIST_DIR}/protocols/xdg-shell.xml)
set(XDG_SHELL_PROTOCOL_HEADER ${GENERATED_DIR}/xdg-shell-client-protocol.hh)
set(GENERATED_XDG_SHELL_PROTOCOL ${GENERATED_DIR}/xdg-shell-protocol.c)
set(POINTER_CONSTRAINTS_PROTOCOL_XML ${CMAKE_CURRENT_LIST_DIR}/protocols/pointer-constraints-unstable-v1.xml)
set(POINTER_CONSTRAINTS_PROTOCOL_HEADER ${GENERATED_DIR}/pointer-constraints-unstable-v1-client-protocol.hh)
set(GENERATED_POINTER_CONSTRAINTS_PROTOCOL ${GENERATED_DIR}/pointer-constraints-unstable-v1-protocol.c)
set(RELATIVE_POINTER_PROTOCOL_XML ${CMAKE_CURRENT_LIST_DIR}/protocols/relative-pointer-unstable-v1.xml)
set(RELATIVE_POINTER_PROTOCOL_HEADER ${GENERATED_DIR}/relative-pointer-unstable-v1-client-protocol.hh)
set(GENERATED_RELATIVE_POINTER_PROTOCOL ${GENERATED_DIR}/relative-pointer-unstable-v1-protocol.c)

add_custom_command(
    OUTPUT ${XDG_OUTPUT_PROTOCOL_HEADER}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} client-header ${XDG_OUTPUT_PROTOCOL_XML} ${XDG_OUTPUT_PROTOCOL_HEADER}
    DEPENDS ${XDG_OUTPUT_PROTOCOL_XML}
    VERBATIM
)

add_custom_command(
    OUTPUT ${GENERATED_XDG_OUTPUT_PROTOCOL}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} public-code ${XDG_OUTPUT_PROTOCOL_XML} ${GENERATED_XDG_OUTPUT_PROTOCOL}
    DEPENDS ${XDG_OUTPUT_PROTOCOL_XML}
    VERBATIM
)

add_custom_command(
    OUTPUT ${XDG_SHELL_PROTOCOL_HEADER}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} client-header ${XDG_SHELL_PROTOCOL_XML} ${XDG_SHELL_PROTOCOL_HEADER}
    DEPENDS ${XDG_SHELL_PROTOCOL_XML}
    VERBATIM
)

add_custom_command(
    OUTPUT ${GENERATED_XDG_SHELL_PROTOCOL}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} public-code ${XDG_SHELL_PROTOCOL_XML} ${GENERATED_XDG_SHELL_PROTOCOL}
    DEPENDS ${XDG_SHELL_PROTOCOL_XML}
    VERBATIM
)

add_custom_command(
    OUTPUT ${POINTER_CONSTRAINTS_PROTOCOL_HEADER}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} client-header ${POINTER_CONSTRAINTS_PROTOCOL_XML} ${POINTER_CONSTRAINTS_PROTOCOL_HEADER}
    DEPENDS ${POINTER_CONSTRAINTS_PROTOCOL_XML}
    VERBATIM
)

add_custom_command(
    OUTPUT ${GENERATED_POINTER_CONSTRAINTS_PROTOCOL}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} public-code ${POINTER_CONSTRAINTS_PROTOCOL_XML} ${GENERATED_POINTER_CONSTRAINTS_PROTOCOL}
    DEPENDS ${POINTER_CONSTRAINTS_PROTOCOL_XML}
    VERBATIM
)

add_custom_command(
    OUTPUT ${RELATIVE_POINTER_PROTOCOL_HEADER}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} client-header ${RELATIVE_POINTER_PROTOCOL_XML} ${RELATIVE_POINTER_PROTOCOL_HEADER}
    DEPENDS ${RELATIVE_POINTER_PROTOCOL_XML}
    VERBATIM
)

add_custom_command(
    OUTPUT ${GENERATED_RELATIVE_POINTER_PROTOCOL}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${GENERATED_DIR}
    COMMAND ${WAYLAND_SCANNER} public-code ${RELATIVE_POINTER_PROTOCOL_XML} ${GENERATED_RELATIVE_POINTER_PROTOCOL}
    DEPENDS ${RELATIVE_POINTER_PROTOCOL_XML}
    VERBATIM
)

add_custom_target(wayland-protocols-codegen
    DEPENDS
      ${XDG_OUTPUT_PROTOCOL_HEADER}
      ${GENERATED_XDG_OUTPUT_PROTOCOL}
      ${XDG_SHELL_PROTOCOL_HEADER}
      ${GENERATED_XDG_SHELL_PROTOCOL}
      ${POINTER_CONSTRAINTS_PROTOCOL_HEADER}
      ${GENERATED_POINTER_CONSTRAINTS_PROTOCOL}
      ${RELATIVE_POINTER_PROTOCOL_HEADER}
      ${GENERATED_RELATIVE_POINTER_PROTOCOL}
)

add_library(jwm SHARED ${SOURCES_OBJC} ${SOURCES_CXX} ${SOURCES_CXX_IMPL} ${GENERATED_XDG_OUTPUT_PROTOCOL} ${GENERATED_XDG_SHELL_PROTOCOL} ${GENERATED_POINTER_CONSTRAINTS_PROTOCOL} ${GENERATED_RELATIVE_POINTER_PROTOCOL})
add_dependencies(jwm wayland-protocols-codegen)
find_library(WAYLAND_CLIENT_LIB wayland-client HINTS ENV LD_LIBRARY_PATH REQUIRED)
find_library(WAYLAND_CURSOR_LIB wayland-cursor HINTS ENV LD_LIBRARY_PATH REQUIRED)
find_library(WAYLAND_EGL_LIB wayland-egl HINTS ENV LD_LIBRARY_PATH REQUIRED)
find_library(EGL_LIB EGL HINTS ENV LD_LIBRARY_PATH REQUIRED)
find_library(OPENGL_LIB GL HINTS ENV LD_LIBRARY_PATH REQUIRED)
find_library(XKBCOMMON_LIB xkbcommon HINTS ENV LD_LIBRARY_PATH REQUIRED)

set(JAVA_HOME $ENV{JAVA_HOME})
if (NOT JAVA_HOME)
    file(GLOB JAVA_HOMES "/usr/lib/jvm/java-*")
    if (JAVA_HOMES)
        list(GET JAVA_HOMES 0 JAVA_HOME)
        message(STATUS "Java home found automatically at ${JAVA_HOME}. Set JAVA_HOME environment variable to override.")
    else()
        message(FATAL_ERROR "Java home not found! Please set JAVA_HOME environment variable.")
    endif()
endif()

target_include_directories(jwm PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../shared/cc ${JAVA_HOME}/include ${JAVA_HOME}/include/linux ${GENERATED_DIR})
set_target_properties(jwm PROPERTIES OUTPUT_NAME "jwm_wayland_${JWM_ARCH}")
target_link_libraries(jwm PRIVATE ${WAYLAND_CLIENT_LIB} ${WAYLAND_CURSOR_LIB} ${WAYLAND_EGL_LIB} ${EGL_LIB} ${OPENGL_LIB} ${XKBCOMMON_LIB})
